version: '3'
services:
  mongo-app:
    image: daya2023/daya-hospital-mongo:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      spring.data.mongodb.uri: mongodb://mongo:27017/data
    depends_on:
      - mongo
    networks:
      - mongo-network
  mongo:
    image: mongo:3.4.7
    ports:
      - "27018:27018"
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge